### PR TITLE
Added the script for automating the process of publishing to pypi using Github Actions

### PR DESCRIPTION
**Pull request by Shamik1836**
Only One needs to add the  two api keys by creating an account on pypi.org and test-pypi.org under the secrets in the repo

### CODE REVIEW

**Comment by nkilm** [comment]
#### The _script is not configured for this project_. Please make the required changes.

#### NOTE: All commits are to be `squashed` to single commit bearing meaningful message(adding description is optional, but recommended) 
> [How do I squash my last N commits together?](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together#:~:text=2752-,Use%20git%20rebase%20%2Di%20%3Cafter%2Dthis%2Dcommit%3E%20and%20replace%20%22pick%22%20on%20the%20second%20and%20subsequent%20commits%20with%20%22squash%22%20or%20%22fixup%22%2C%20as%20described%20in%20the%20manual.,-In%20this%20example)

**Comment by Shamik1836** [comment]
Please have a look @nkilm if it's right or not this time?

**Comment by nkilm** [comment]
#### Commits not squashed.

**Comment by Shamik1836** [comment]
Ok doing that

**Comment by Shamik1836** [comment]
I have squashed the three last commit messages into one, please have  a look now @nkilm

**Comment by nkilm** [comment]
Where? I see 3 commits listed. Try doing force push with `-f` flag.

**Comment by Shamik1836** [comment]
I think now it's done finally @nkilm

**Comment by nkilm** [comment]
Yes, good. I think you squashed one of my commits also, nevermind.

**Pull request merged**
